import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SessionProvider } from "next-auth/react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-slate-800">
        <SessionProvider
        
        refetchInterval={5 * 60} // 5 minutes
        refetchOnWindowFocus={true}>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
